#!/bin/bash

# Installs zj-58 driver
# Tested as working under MacOS 10.13.1

sudo launchctl stop org.cups.cupsd
cp rastertozj /usr/libexec/cups/filter/
mkdir -p /usr/share/cups/model/zjiang
cp zj-80.ppd /usr/share/cups/model/zjiang/
cd /usr/libexec/cups/filter
chmod 755 rastertozj
chown root:wheel rastertozj
cd -
sudo launchctl start org.cups.cupsd